### ISSUE TITLE
Return AGI error if call not answered

### ISSUE THREAD

**Issue by jsgoecke** [tropo/tropo-agitate#1]
Right now if you issue a command, like play, on an unanswered channel you see this in the Tropo log:

00919      c117       01:06:45 AM    Call[verendusf80a822->9991479153] : ====> Error: Unable to execute the 200 result=-1 request. call_active?: true <====
00920      c117       01:06:45 AM    Call[verendusf80a822->9991479153] : ====> Error output:: #<RuntimeError: com.voxeo.tropo.core.NotAnsweredException: RINGING> <====

Should throw an appropriate AGI error and think about auto-answering like Asterisk does.

**Comment by bklang** [comment]
In many cases Asterisk applications will silently answer the channel if the channel is not already answered and the channel must be answered for the application to work.  This is somewhat arbitrary and varies from application to application.  In point of fact, the "Playback" application accepts arguments on which to do (the default is to silently answer the channel, but it has options to either skip playing if the channel is not answered or to explicitly not answer the channel and try to play the sound anyway).  One use of this may be to send early media, but I'm not sure if/how that would work with Tropo.

**Comment by jsgoecke** [comment]
In this case it does return a:

DEBUG agi: >>> STREAM FILE "tt-monkeys" "1234567890*#"
DEBUG agi: <<< 200 result=-1

What should it be returning as the appropriate value if not '-1' for this? I know probably different by app...

**Comment by jsgoecke** [comment]
AGItate will now auto-answer on the appropriate methods:

http://github.com/tropo/tropo-agitate/commit/9998bff1d886174fba18105b81f1eb2f6ffa5e78

**Comment by bklang** [comment]
Instead of "200 result=-1" the best way to signal a protocol error is a 5XX.  For example, if you send a command to a hung-up channel you'll get back "511 Command Not Permitted on a dead channel".

The auto answer in several general cases (like playing a sound file) makes sense as Asterisk has a similar behavior.

**Comment by jsgoecke** [comment]
Thanks. Opened this particular point as a new ticket:

http://github.com/tropo/tropo-agitate/issues/#issue/6
