### ISSUE TITLE
STREAM FILE should allow interruption by DTMF

### ISSUE THREAD

**Issue by bklang** [tropo/tropo-agitate#2]
Using the "input" command in Adhearsion results in a STREAM FILE AGI command.  This command is intended to be interrupted by DTMF input.  When using AGItate the user must wait until the audio is complete before Tropo starts listening for DTMF input.

**Comment by jsgoecke** [comment]
Good point, will fix. In the meantime you may call an ask directly as opposed to input:

execute "ask", options_hash 

See for available options:

https://www.tropo.com/docs/scripting/ask.htm

**Comment by jsgoecke** [comment]
STREAM FILE now allows a DTMF interrupt with this commit:

http://github.com/tropo/tropo-agitate/commit/1fce7ba0e84d4898a54635e33bd7b25bb58c7455

Now looking about returning the digit from that STREAM FILE.

**Comment by jsgoecke** [comment]
Now returns the digit used to interrupt the STREAM FILE

http://github.com/tropo/tropo-agitate/commit/b03c2cf701d87316cf849abeabc359e7d7e10434
