### ISSUE TITLE
WAIT FOR DIGIT incorrectly multiplies input

### ISSUE THREAD

**Issue by bklang** [tropo/tropo-agitate#4]
WAIT FOR DIGIT is supposed to accept a wait timer in milliseconds.  Adhearsion already sends the time in milliseconds, but AGItate multiplies that number again, causing this:
input => 1, :timeout => 5

to turn into this:

```
14603       7d0f       02:04:23 AM       Call[4044754841->3108959449] : ====> command: {:action=>"wait", :command=>"for", :args=>["DIGIT \"5000"]} <====
14604       7d0f       02:04:23 AM       Call[4044754841->3108959449] : _parseTime(5) returning 5000
14605       7d0f       02:04:23 AM       Call[4044754841->3108959449] : _parseTime(5000) returning 5000000
14606       7d0f       02:04:23 AM       Call[4044754841->3108959449]->prompt("",true,"[1 DIGIT]","",0.3,keypad,5000000)
```

Causing the user to wait 5,000 seconds.

**Comment by jsgoecke** [comment]
I have been able to recreate this and am investigating.

**Comment by bklang** [comment]
Fixed in the latest pull request https://github.com/tropo/tropo-agitate/pull/17
